# Generated by Django 6.0.7 on 2026-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_room_capacity_alter_room_price_per_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
