# Generated by Django 6.0.7 on 2026-07-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_alter_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
    ]
